### ISSUE TITLE
Does this support Gimbal sdk v4?

### ISSUE THREAD

**Issue by melbaldove** [urbanairship/android-gimbal-adapter#10]
Does this support Gimbal sdk v4 for Android?

**Comment by rlepinski** [comment]
I was able to start the plugin and get a gimbal instance id using v4 of Gimbal. Due to how Gimbal versions the group you need to exclude v3 of Gimbal from our adapter and pull in the v4:

```
    implementation('com.urbanairship.android:gimbal-adapter:2.2.0') {
        exclude group: 'com.gimbal.android.v3'
    }

    implementation 'com.gimbal.android.v4:gimbal-sdk:4.0.1'
    implementation 'com.gimbal.android.v4:gimbal-slf4j-impl:4.0.1'
```

**Comment by BrianBatchelder** [comment]
@MelbyBaldove : I'm going to close this issue now. If you are continuing to see this problem, please re-open the issue. If you have a different issue, please submit a new issue. Thank you.
