### ISSUE TITLE
Gimbal adapter crash while calling GimbalAdapter.stop() method

### ISSUE THREAD

**Issue by harishrpatel** [urbanairship/android-gimbal-adapter#12]
- We are using Gimbal Adapter version 3.0.0 with Airship SDK 11.0.3.

Here is our code usage:

open class OurApplication: Application() {

    protected fun onAppBackgrounded() {
        GimbalAdapter.shared(this).stop()
    }

}

Here is the crash log:
Caused by java.lang.IllegalStateException: Android context not initialized yet. Call setApiKey before calling any other method.
       at com.qsl.faar.service.a.a + 71(SourceFile:71)
       at com.gimbal.android.PlaceManager.<init> + 65(SourceFile:65)
       at com.gimbal.android.PlaceManager.getInstance + 59(SourceFile:59)
       at com.gimbal.android.Gimbal.stop + 88(SourceFile:88)
       at com.urbanairship.gimbal.GimbalAdapter.stop + 291(GimbalAdapter.java:291)
       at ......onAppBackgrounded(....)
...

**Comment by rlepinski** [comment]
Thanks for the report. Is it possible you are calling `stop` without a call to `start` ? Any steps to reproduce?

**Comment by harishrpatel** [comment]
It is happening a lot in the field but we cannot reproduce it. We are trying to check ifStarted then only call this. Can you look into this qsl library and confirm if that is the only reason it would throw this exception? Thanks.

**Comment by rlepinski** [comment]
We do not own that library but I will reach out to the Gimbal team. The adapter is not checking the `isStarted` flag, and we could catch that exception. We will try to get a fix out for early next week.

**Comment by harishrpatel** [comment]
Thank you. We have been fighting some battery drain issues on our app and this stop() call helps little bit.

**Comment by BrianBatchelder** [comment]
@harishrpatel : [Version 4.0.0](https://bintray.com/urbanairship/android/gimbal-adapter/4.0.0) of the Gimbal Adapter has been released to address your issue. Please let us know if you encounter further issues.
