### ISSUE TITLE
Version 6.0.0 is not presence in Maven repo

### ISSUE THREAD

**Issue by ZakharSS** [urbanairship/android-gimbal-adapter#19]
Hi, I failed to get the latest version for Android project. Error "Failed to resolve: com.urbanairship.android:gimbal-adapter:6.0.0". But 5.0.0 is ok. Could you upload version 6.0.0 to the Maven repository? Thank you!

**Comment by rlepinski** [comment]
Thanks for letting us know. Should be fixed.
