### ISSUE TITLE
GimbalServiceStartStopReceiver needs android:exported explicitly set for Android 12

### ISSUE THREAD

**Issue by mcezat** [urbanairship/android-gimbal-adapter#24]
When targeting Android 12 and attempting to install on an Android 12 device, I receive this error message:

`Installation failed due to: 'Failed to commit install session 129806999 with command cmd package install-commit 129806999. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl129806999.tmp/base.apk (at Binary XML file line #872): com.gimbal.internal.service.GimbalServiceStartStopReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'
`

As the error message says, I believe you need to explicitly set the "android:exported" attribute explicitly in the manifest file where you declare GimbalServiceStartStopReceiver.

This is blocking anyone that uses this SDK from targeting Android 12 and running it on an Android 12 device.

**Comment by rlepinski** [comment]
This is a Gimbal issue. Ill try to reach out to the Gimbal team to see if they have any updates.

**Comment by jyaganeh** [comment]
Hi @mcezat, we just released version `7.2.0`, which includes the latest Gimbal SDK with fixes for targeting Android 12. The new version was published to Maven Central and may take a few moments to become available for download. You'll also need to add `mavenCentral()` to the `repositories` block in your `build.gradle` file, if it's not already there.
